### ISSUE TITLE
Fix LD_LIBRARY_PATH in README.md for running cgoase

### ISSUE THREAD

**Issue by hqin** [SAP/cgo-ase#15]
**Description**
The instruction in README.md for executing cgoase is incorrect.

LD_LIBRARY_PATH="/path/to/OCS/lib" ./cgoase 
should be 
LD_LIBRARY_PATH="/path/to/OCS/lib:/path/to/OCS/lib3p:/path/to/OCS/lib3p64:" ./cgoase 

**Expected behaviour**

./cgoase should return without error

**Current behaviour**

LD_LIBRARY_PATH="/path/to/OCS/lib" ./cgoase
returns login error

**Steps to Reproduce**

LD_LIBRARY_PATH="/path/to/OCS/lib" ./cgoase
returns error:
``
Msg 67241519: ct_connect(): protocol specific layer: internal Client Library error: There is a tds login error. The installed encryption handler returned a status that was not CS_SUCCEED.
Msg 16843068: ct_close(): user api layer: external error: There is a usage error.  This routine has been called at an illegal time.
cgoase failed: failed to connect to database: Failed to open connection: C.ct_connect failed: Routine failed
``
Changing LD_LIBRARY_PATH
LD_LIBRARY_PATH="/path/to/OCS/lib:/path/to/OCS/lib3p:/path/to/OCS/lib3p64:" ./cgoase 
returns without error

**Environment**

Client:
  OS: CentOS Linux release 7.6.1810
  go version: 1.15.0
  cgo-ase version / commit hash: be6a2f61e12da18bb374a5cf638f109e28c8e512
  go-dblib version / commit hash: github.com/SAP/go-dblib v0.0.0-20210114120425-3f210eb9fa26

Server:
  OS: CentOS 
  ASE version: 16.0_SP03PL02_EBF28306.el7

**Comment by fwilhelm92** [comment]
Hi Huajun,

Thanks for your issue!

We created the code based on ASE releases greater than `SAP Adaptive Server Enterprise for Business Suite 16.0.03.07` and this error never occurred. Therefore, one possible solution would be to upgrade your release. 

However, I'll try to get this older release and try to replicate your issue.

**Comment by fwilhelm92** [comment]
We were able to replicate the issue. Thanks for your contribution!
