### ISSUE TITLE
Connection properties do not work as described in README.md

### ISSUE THREAD

**Issue by hqin** [SAP/cgo-ase#20]
**Description**

Connection properties do not work as described in README.md

**Expected behaviour**

"log-client-msgs" is a bool, but described as string in README
"log-server-msgs" is a bool, but described as string in README
"channel-package-queue-size=110" returns: error parsing DSN: no field for key "channel-package-queue-size"

Both cgo-ase and go-ase should support the same set of connection properties, even if some properties result in no-op for a driver. This would allow developers to switch drivers without changing code. Both drivers register as 'ase', and should behave the same (expect performance differences) at the API level.

**Current behaviour**

A clear and concise description of what currently happens.

**Steps to Reproduce**

**Environment**

Client:
  OS:
  go version: 1.16.3
  cgo-ase version / commit hash: v0.0.0-20210312084010-d645a8f3e9d9
  go-dblib version / commit hash: v0.0.0-20210315102028-46975ce12d39

Server:
  OS:
  ASE version:  16.0_SP03PL02_EBF28306.el7

**Screenshots**

**Additional context**

**Comment by hqin** [comment]
Would like to see "appname", "no-query-cursor", etc. in go-ase driver to work in cgo-ase.
In reverse, "log-client-msgs" and "log-server-msgs" in cgo-ase are extremely useful for trouble shooting, and they should in be in go-ase as well

**Comment by ntnn** [comment]
Thank you, the documentation and the AppName property has been added.

Regarding the other points see my response here: https://github.com/SAP/go-ase/issues/194#issuecomment-831233661
